import type { TBudget, TCategory, TTransaction } from '@/types/models';

export const transactions: TTransaction[] = [
    {
        id: '1',
        kind: 'expense',
        amount: 85.5,
        category: 'Food',
        description: 'Grocery shopping at Whole Foods',
        date: '2024-01-15',
        tags: ['groceries', 'essential'],
    },
    {
        id: '2',
        kind: 'income',
        amount: 3500.0,
        category: 'Salary',
        description: 'Monthly salary',
        date: '2024-01-01',
        tags: ['work'],
    },
    {
        id: '3',
        kind: 'expense',
        amount: 1200.0,
        category: 'Rent',
        description: 'Monthly rent payment',
        date: '2024-01-01',
        tags: ['housing', 'fixed'],
    },
    {
        id: '4',
        kind: 'expense',
        amount: 45.0,
        category: 'Transport',
        description: 'Gas station fill-up',
        date: '2024-01-14',
        tags: ['car', 'fuel'],
    },
    {
        id: '5',
        kind: 'expense',
        amount: 120.0,
        category: 'Entertainment',
        description: 'Movie tickets and dinner',
        date: '2024-01-13',
        tags: ['leisure', 'social'],
    },
    {
        id: '6',
        kind: 'expense',
        amount: 65.0,
        category: 'Utilities',
        description: 'Electricity bill',
        date: '2024-01-10',
        tags: ['bills', 'fixed'],
    },
    {
        id: '7',
        kind: 'expense',
        amount: 32.5,
        category: 'Food',
        description: 'Coffee and pastry',
        date: '2024-01-12',
        tags: ['coffee', 'breakfast'],
    },
    {
        id: '8',
        kind: 'income',
        amount: 250.0,
        category: 'Freelance',
        description: 'Web design project',
        date: '2024-01-08',
        tags: ['freelance', 'design'],
    },
    {
        id: '9',
        kind: 'expense',
        amount: 89.99,
        category: 'Shopping',
        description: 'New running shoes',
        date: '2024-01-07',
        tags: ['clothing', 'fitness'],
    },
    {
        id: '10',
        kind: 'expense',
        amount: 15.0,
        category: 'Transport',
        description: 'Uber ride to airport',
        date: '2024-01-06',
        tags: ['travel', 'uber'],
    },
];

export const budgets: TBudget[] = [
    {
        id: '1',
        category: 'Food',
        amount: 500,
        spent: 318.0,
        period: 'monthly',
    },
    {
        id: '2',
        category: 'Transport',
        amount: 200,
        spent: 60.0,
        period: 'monthly',
    },
    {
        id: '3',
        category: 'Entertainment',
        amount: 300,
        spent: 120.0,
        period: 'monthly',
    },
    {
        id: '4',
        category: 'Utilities',
        amount: 150,
        spent: 65.0,
        period: 'monthly',
    },
    {
        id: '5',
        category: 'Shopping',
        amount: 400,
        spent: 89.99,
        period: 'monthly',
    },
];

export const categories: TCategory[] = [
    {
        id: '1',
        name: 'Food',
        kind: 'expense',
        color: '#f59e0b',
        transaction_count: 2,
        total_amount: 118.0,
    },
    {
        id: '2',
        name: 'Rent',
        kind: 'expense',
        color: '#dc2626',
        transaction_count: 1,
        total_amount: 1200.0,
    },
    {
        id: '3',
        name: 'Transport',
        kind: 'expense',
        color: '#059669',
        transaction_count: 2,
        total_amount: 60.0,
    },
    {
        id: '4',
        name: 'Entertainment',
        kind: 'expense',
        color: '#7c3aed',
        transaction_count: 1,
        total_amount: 120.0,
    },
    {
        id: '5',
        name: 'Salary',
        kind: 'income',
        color: '#10b981',
        transaction_count: 1,
        total_amount: 3500.0,
    },
    {
        id: '6',
        name: 'Utilities',
        kind: 'expense',
        color: '#4b5563',
        transaction_count: 1,
        total_amount: 65.0,
    },
    {
        id: '7',
        name: 'Freelance',
        kind: 'income',
        color: '#06b6d4',
        transaction_count: 1,
        total_amount: 250.0,
    },
    {
        id: '8',
        name: 'Shopping',
        kind: 'expense',
        color: '#8b5cf6',
        transaction_count: 1,
        total_amount: 89.99,
    },
];
