import type { TBudget, TTransaction } from '@/types/models';
import type { TIndexCategory } from '@/types/props';

export const transactions: TTransaction[] = [
    {
        id: 1,
        kind: 'expense',
        amount: 85.5,
        category: 'Food',
        description: 'Grocery shopping at Whole Foods',
        date: '2024-01-15',
        tags: ['groceries', 'essential'],
    },
    {
        id: 2,
        kind: 'income',
        amount: 3500.0,
        category: 'Salary',
        description: 'Monthly salary',
        date: '2024-01-01',
        tags: ['work'],
    },
    {
        id: 3,
        kind: 'expense',
        amount: 1200.0,
        category: 'Rent',
        description: 'Monthly rent payment',
        date: '2024-01-01',
        tags: ['housing', 'fixed'],
    },
    {
        id: 4,
        kind: 'expense',
        amount: 45.0,
        category: 'Transportation',
        description: 'Gas for car',
        date: '2024-01-10',
        tags: ['fuel', 'transport'],
    },
    {
        id: 5,
        kind: 'expense',
        amount: 25.0,
        category: 'Entertainment',
        description: 'Movie tickets',
        date: '2024-01-12',
        tags: ['leisure', 'cinema'],
    },
    {
        id: 6,
        kind: 'income',
        amount: 500.0,
        category: 'Freelance',
        description: 'Web development project',
        date: '2024-01-08',
        tags: ['freelance', 'work'],
    },
    {
        id: 7,
        kind: 'expense',
        amount: 75.0,
        category: 'Utilities',
        description: 'Electricity bill',
        date: '2024-01-05',
        tags: ['bills', 'utilities'],
    },
    {
        id: 8,
        kind: 'expense',
        amount: 120.0,
        category: 'Food',
        description: 'Dinner at restaurant',
        date: '2024-01-14',
        tags: ['dining', 'food'],
    },
    {
        id: 9,
        kind: 'expense',
        amount: 30.0,
        category: 'Healthcare',
        description: 'Pharmacy purchase',
        date: '2024-01-11',
        tags: ['health', 'medicine'],
    },
    {
        id: 10,
        kind: 'income',
        amount: 200.0,
        category: 'Investment',
        description: 'Dividend payment',
        date: '2024-01-03',
        tags: ['investment', 'dividend'],
    },
];

export const categories: TIndexCategory[] = [
    {
        id: 1,
        user_id: 1,
        name: 'Food',
        kind: 'expense',
        color: '#ef4444',
        transaction_count: 15,
        total_amount: 450.75,
    },
    {
        id: 2,
        user_id: 1,
        name: 'Transportation',
        kind: 'expense',
        color: '#3b82f6',
        transaction_count: 8,
        total_amount: 230.5,
    },
    {
        id: 3,
        user_id: 1,
        name: 'Entertainment',
        kind: 'expense',
        color: '#8b5cf6',
        transaction_count: 5,
        total_amount: 125.0,
    },
    {
        id: 4,
        user_id: 1,
        name: 'Healthcare',
        kind: 'expense',
        color: '#10b981',
        transaction_count: 3,
        total_amount: 180.25,
    },
    {
        id: 5,
        user_id: 1,
        name: 'Salary',
        kind: 'income',
        color: '#f59e0b',
        transaction_count: 12,
        total_amount: 42000.0,
    },
    {
        id: 6,
        user_id: 1,
        name: 'Freelance',
        kind: 'income',
        color: '#06b6d4',
        transaction_count: 4,
        total_amount: 2400.0,
    },
    {
        id: 7,
        user_id: 1,
        name: 'Investment',
        kind: 'income',
        color: '#84cc16',
        transaction_count: 2,
        total_amount: 350.0,
    },
    {
        id: 8,
        user_id: 1,
        name: 'Utilities',
        kind: 'expense',
        color: '#f97316',
        transaction_count: 6,
        total_amount: 480.3,
    },
    {
        id: 9,
        user_id: 1,
        name: 'Rent',
        kind: 'expense',
        color: '#ef4444',
        transaction_count: 1,
        total_amount: 1200.0,
    },
];

export const budgets: TBudget[] = [
    {
        id: 1,
        category_id: 1,
        amount: 500.0,
        period: 'monthly',
        spent: 320.5,
    },
    {
        id: 2,
        category_id: 2,
        amount: 200.0,
        period: 'monthly',
        spent: 150.75,
    },
    {
        id: 3,
        category_id: 3,
        amount: 100.0,
        period: 'weekly',
        spent: 85.25,
    },
    {
        id: 4,
        category_id: 8,
        amount: 150.0,
        period: 'monthly',
        spent: 95.3,
    },
];
